from pathlib import Path

# Contains scripts and notebooks to execute
BIN_DIR = Path('bin/')

# Contains all YAML configuration files
CONFIG_DIR = Path('conf/')

# Contains the functionality and building blocks of the project
LIBRARY_DIR = Path('eyemod/')

# Contains the tess
TEST_DIR = Path('test/')

# Contains data used by th scripts and notebooks 
IN_DIR = Path('in/')

# Contains data generated by the scripts and notebooks
OUT_DIR = Path('out/')

